version: '3.9'

services:
  cloudflared-tunnel:
    container_name: ${CONTAINER_NAME}
    image: cloudflare/cloudflared:2024.3.0
    command: tunnel --url ${ADDRESS}
    networks:
      - network1
networks:
  network1:
    name: ${NETWORK:-tryc}_default
    external: true
