version: '3.9'

services:
  expose:
    build: .
    # command: some-tunnel-1 ""
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ADDRESS: 'http://nginx:80'
  nginx:
    image: nginx:latest
    networks:
      - tryc
networks:
  tryc:
    external: true