version: '3.9'

services:
  cloudflared-tunnel:
    container_name: ${CONTAINER_NAME}
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel --url ${ADDRESS}
    networks:
      - network1
networks:
  network1:
    name: ${NETWORK:-tryc}
    external: true
